name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New Version'
        default: '1.8.1'
        required: true

jobs:

  updateBinaryTarget:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Package.swift
      run: |
        ./scripts/updateChecksum.sh ${{ github.event.inputs.newVersion }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
